-- Generated by _ops/aggregate-artists/build-set-times.mjs — do not edit by hand.
-- 50 set time row(s) from the lineup pages' ACTS data.

update public.artist_festival_appearances ap set
  start_at = coalesce(case when v.start_local is null then null else v.start_local::timestamp at time zone f.timezone end, ap.start_at),
  end_at = case when v.start_local is null then ap.end_at when v.end_local is null then null else v.end_local::timestamp at time zone f.timezone end,
  stage = coalesce(v.stage, ap.stage)
from (values
  ('lost-in-dreams-los-angeles-2026', 'covex', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'julienne by', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'madi', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'sober rob', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'sportmode', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'babsy.', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'chet porter', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'elohim', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'sabai', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'jason ross', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'blanke', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'manila killa', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'aobeats', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'robokid', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'baauer', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'william black', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'louis the child', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'what so not', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'porter robinson', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'yung bae', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'alvyn', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'discovery project', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'sky sky', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'tfti', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'elephante', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'iznyrs', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'wavedash', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'johnny chay', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'jvna', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'rayray', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'yetep', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'armnhmr', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'jvna', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'audien', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'raiden', null, null, 'Vivid'),
  ('lost-in-dreams-los-angeles-2026', 'dabin', null, null, 'Lucid'),
  ('lost-in-dreams-los-angeles-2026', 'hyo', null, null, 'Vivid'),
  ('night-trip-arizona-2026', 'cloonee', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'chris lorenzo', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'sidepiece', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'omnom', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'marco strous', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'valeri stoss', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'peachy keen', null, null, 'High Tide'),
  ('night-trip-arizona-2026', 'loco dice', null, null, 'Deep End'),
  ('night-trip-arizona-2026', 'chasewest', null, null, 'Deep End'),
  ('night-trip-arizona-2026', 'discip', null, null, 'Deep End'),
  ('night-trip-arizona-2026', 'ragie ban', null, null, 'Deep End'),
  ('night-trip-arizona-2026', 'welker', null, null, 'Deep End'),
  ('night-trip-arizona-2026', 'tommy toole', null, null, 'Deep End')
) as v(slug, name_lower, start_local, end_local, stage)
join public.festivals f on f.slug = v.slug and f.deleted_at is null
join public.artists a on a.name_lower = v.name_lower
where ap.festival_id = f.id and ap.artist_id = a.id
  and (v.start_local is null or f.timezone is not null);
